### ISSUE TITLE
Redundant formulas with hombrew-science

### ISSUE THREAD

**Issue by magicDGS** [vetmeduni/homebrew-popgen#26]
Although the former [Homebrew/hombrew-science](https://github.com/Homebrew/homebrew-science) repository is archived now, there is a new one called [brewsci/homebrew-science](https://github.com/brewsci/homebrew-science). Thus, there are some formulas that are replicated here and it is better to remove to do not overload maintenance of them:

- [ ] freebayes
- [ ] stacks
- [x] vcflib

**Comment by magicDGS** [comment]
Sorry, not really true. The organization is planning to maintain the bioinformatics software in https://github.com/brewsci/homebrew-bio

**Comment by magicDGS** [comment]
But they don't have the formulas added there yet!

**Comment by robmaz** [comment]
Vcflib showed up and I deleted ours yesterday. Will delete the others as/if they come.

**Comment by robmaz** [comment]
Deleted remaining formulas maintened in brewsci in #69
