### ISSUE TITLE
New formula for PoPoolation TE2

### ISSUE THREAD

**Issue by magicDGS** [vetmeduni/homebrew-popgen#3]
This should be easy, because it is another uber-jar based software as `ReadTools`, so a simple wrapper script may be enough.

PoPoolation TE2 repository: https://sourceforge.net/p/popoolation-te2/wiki/Home/

**Comment by robmaz** [comment]
I just pushed a formula for popte2.

**Comment by magicDGS** [comment]
Looking forward to the PR!

**Comment by magicDGS** [comment]
This is done.
