### ISSUE TITLE
Fix brew audit errors in current formulae (strict)

### ISSUE THREAD

**Issue by magicDGS** [vetmeduni/homebrew-popgen#51]
## art:
  * C: 14: col 1: Trailing whitespace detected.
  * C: 40: col 1: Extra empty line detected at method body end.
  * C: 57: col 1: Extra empty line detected at class body end.
Error: 3 problems in 1 formula

## ddocent:
  * C: 7: col 3: Commented-out dependency "freebayes" => :run
  * C: 8: col 3: Commented-out dependency "stacks" => :run
  * C: 9: col 3: Commented-out dependency "trimmomatic" => :run
  * C: 10: col 3: Commented-out dependency "mawk" => :run
  * C: 11: col 3: Commented-out dependency "bwa" => :run
  * C: 12: col 3: Commented-out dependency "samtools" => :run
  * C: 13: col 3: Commented-out dependency "vcftools" => :run
  * C: 14: col 3: Commented-out dependency "rainbow" => :run
  * C: 15: col 3: Commented-out dependency "seqtk" => :run
  * C: 16: col 3: Commented-out dependency "cd-hit" => :run
  * C: 17: col 3: Commented-out dependency "bedtools" => :run
  * C: 18: col 3: Commented-out dependency "vcflib" => :run
  * C: 19: col 3: Commented-out dependency "gnuplot" => :run
  * C: 20: col 3: Commented-out dependency "parallel" => :run
  * C: 21: col 3: Commented-out dependency "bamtools" => :run
  * C: 22: col 3: Commented-out dependency :java => :run
  * C: 23: col 3: Commented-out dependency "pear" => :run
Error: 17 problems in 1 formula

## popte2:
  * C: 2: col 3: Description is too long. "name: desc" should be less than 80 characters. Length is calculated as popte2 + desc. (currently 361)
  * C: 5: col 55: Description shouldn't end with a full stop
Error: 2 problems in 1 formula

## readtools@1.0:
  * C: 9: col 3: `bottle` (line 9) should be put before `keg_only` (line 7)
Error: 1 problem in 1 formula

**Comment by robmaz** [comment]
Done in #73
